/**
 * Phase 27: the feature completeness assessment against the feature catalogue.
 *
 *   node apps/web/scripts/completeness.mjs index [--catalogue ~/wesnoth-feature-catalogue.md]
 *   node apps/web/scripts/completeness.mjs report
 *
 * `index` numbers the catalogue's items (`<category>.<n>`, in document order) into
 * `docs/completeness/catalogue-index.json`: id, category, title and the WML hooks. The catalogue itself
 * stays outside the repo; only these are kept.
 *
 * `report` joins the index with the assessment (`docs/completeness/assessment.json`: per id a status --
 * done, partial, missing or out-of-scope -- the evidence and a note) into `docs/COMPLETENESS.md`. Each
 * piece of evidence is a repo path (a test, a browser script, a source file), optionally `path#name`;
 * every path must exist. Exits non-zero when an assessed id is not in the index, a status is unknown, or
 * an evidence path is missing. Unassessed items are listed as such, and counted. The hand-written findings
 * (`docs/completeness/summary.md`) go under the summary table.
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const dir = path.join(repoRoot, 'docs/completeness');
const indexFile = path.join(dir, 'catalogue-index.json');
const assessmentFile = path.join(dir, 'assessment.json');
const reportFile = path.join(repoRoot, 'docs/COMPLETENESS.md');

const STATUSES = ['done', 'partial', 'missing', 'out-of-scope'];
const LABEL = { done: 'Done', partial: 'Partial', missing: 'Missing', 'out-of-scope': 'Out of scope', unassessed: 'Not yet assessed' };

const args = process.argv.slice(2);
const arg = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : fallback;
};

function index() {
  const file = arg('catalogue', path.join(homedir(), 'wesnoth-feature-catalogue.md'));
  const lines = readFileSync(file, 'utf8').split('\n');
  const categories = [];
  const items = [];
  let category = null;
  let n = 0;
  for (const line of lines) {
    const heading = /^## (\d+)\. (.+)$/.exec(line);
    if (heading) {
      category = Number(heading[1]);
      n = 0;
      categories.push({ id: category, name: heading[2].trim() });
      continue;
    }
    if (/^## /.test(line)) {
      category = null; // the appendices
      continue;
    }
    if (category === null) continue;
    const item = /^- \*\*(.+?)\*\*\s*$/.exec(line);
    if (item) {
      items.push({ id: `${category}.${++n}`, category, title: item[1].trim(), wml: '' });
      continue;
    }
    const wml = /^ {2}- \*WML:\*\s*(.*)$/.exec(line);
    if (wml && items.length > 0) items[items.length - 1].wml = wml[1].trim();
  }
  writeFileSync(indexFile, `${JSON.stringify({ categories, items }, null, 1)}\n`);
  console.log(`${items.length} items in ${categories.length} categories -> ${path.relative(repoRoot, indexFile)}`);
}

const cell = (s) => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');

function report() {
  const { categories, items } = JSON.parse(readFileSync(indexFile, 'utf8'));
  const assessment = existsSync(assessmentFile) ? JSON.parse(readFileSync(assessmentFile, 'utf8')) : {};
  const problems = [];
  const ids = new Set(items.map((i) => i.id));
  for (const [id, a] of Object.entries(assessment)) {
    if (!ids.has(id)) problems.push(`${id}: not in the catalogue index`);
    if (!STATUSES.includes(a.status)) problems.push(`${id}: unknown status "${a.status}"`);
    for (const e of a.evidence ?? []) {
      const p = e.split('#')[0];
      if (!existsSync(path.join(repoRoot, p))) problems.push(`${id}: evidence ${p} does not exist`);
    }
    if (a.status !== 'done' && !a.note) problems.push(`${id}: a ${a.status} item needs a note`);
  }

  const statusOf = (item) => assessment[item.id]?.status ?? 'unassessed';
  const tally = (list) => {
    const t = { done: 0, partial: 0, missing: 0, 'out-of-scope': 0, unassessed: 0 };
    for (const i of list) t[statusOf(i)]++;
    return t;
  };
  const all = tally(items);
  const out = [];
  out.push('# Feature completeness');
  out.push('');
  out.push('Phase 27: every item of the feature catalogue (`~/wesnoth-feature-catalogue.md`), classified against the port.');
  out.push('Generated by `node apps/web/scripts/completeness.mjs report` from `docs/completeness/assessment.json`; edit that, not this.');
  out.push('');
  out.push('- **Done**: a real implementation with a test, a browser check or shipped content that exercises it.');
  out.push('- **Partial**: implemented in part, or implemented with nothing that exercises it; the note says what is missing.');
  out.push('- **Missing**: not implemented.');
  out.push('- **Out of scope**: deliberately not part of the port; the note says why.');
  out.push('');
  out.push('## Summary');
  out.push('');
  out.push('| # | Category | Items | Done | Partial | Missing | Out of scope | Not yet assessed |');
  out.push('|---|---|---|---|---|---|---|---|');
  for (const c of categories) {
    const t = tally(items.filter((i) => i.category === c.id));
    out.push(`| ${c.id} | [${c.name}](#${c.id}-${c.name.toLowerCase().replace(/[^a-z0-9 -]/g, '').replace(/ /g, '-')}) | ${t.done + t.partial + t.missing + t['out-of-scope'] + t.unassessed} | ${t.done} | ${t.partial} | ${t.missing} | ${t['out-of-scope']} | ${t.unassessed} |`);
  }
  out.push(`| | **All** | **${items.length}** | **${all.done}** | **${all.partial}** | **${all.missing}** | **${all['out-of-scope']}** | **${all.unassessed}** |`);
  // The findings and follow-ups, written by hand.
  const summaryFile = path.join(dir, 'summary.md');
  if (existsSync(summaryFile)) out.push('', readFileSync(summaryFile, 'utf8').trimEnd());
  for (const c of categories) {
    out.push('');
    out.push(`## ${c.id}. ${c.name}`);
    out.push('');
    out.push('| Id | Feature | Status | Evidence | Note |');
    out.push('|---|---|---|---|---|');
    for (const item of items.filter((i) => i.category === c.id)) {
      const a = assessment[item.id];
      const evidence = (a?.evidence ?? []).map((e) => `\`${e}\``).join('<br>');
      out.push(`| ${item.id} | ${cell(item.title)} | ${LABEL[statusOf(item)]} | ${evidence} | ${cell(a?.note ?? '')} |`);
    }
  }
  writeFileSync(reportFile, `${out.join('\n')}\n`);
  console.log(`${items.length} items: ${all.done} done, ${all.partial} partial, ${all.missing} missing, ${all['out-of-scope']} out of scope, ${all.unassessed} not yet assessed -> ${path.relative(repoRoot, reportFile)}`);
  if (problems.length > 0) {
    console.log(`\n${problems.length} problem(s):\n${problems.map((p) => `  - ${p}`).join('\n')}`);
    process.exit(1);
  }
}

const command = args[0];
if (command === 'index') index();
else if (command === 'report') report();
else {
  console.log('usage: completeness.mjs index [--catalogue file] | report');
  process.exit(1);
}
