/**
 * GENERATED by packages/engine/scripts/gen-ai-configs.mjs -- do not hand-edit.
 * Source: `wesnoth/data/ai/utils/default_config.cfg` and `wesnoth/data/ai/ais/*.cfg`
 * (upstream 1.19.21+dev). See that script's own doc comment for why this is
 * checked in rather than parsed at runtime, and `test/ai/
 * builtinConfigsInSync.test.ts` for the drift check.
 */
import type { WmlConfigJson } from '../../wml/config.js';

/** The `[default_config]` aspect defaults (see `configuration::parse_side_config`): a bare list of `[aspect]` children with no enclosing `[ai]`. */
export const DEFAULT_AI_CONFIG_JSON: WmlConfigJson = {
  "attrs": {},
  "children": [
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "advancements",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "aggression",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 0.4
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "allow_ally_villages",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": false
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "attacks",
          "engine": "cpp",
          "name": "composite_aspect",
          "invalidate_on_gamestate_change": true
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "ai_default_rca::aspect_attacks",
                "invalidate_on_gamestate_change": true
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "avoid",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": [
                {
                  "tag": "value",
                  "config": {
                    "attrs": {},
                    "children": [
                      {
                        "tag": "not",
                        "config": {
                          "attrs": {},
                          "children": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "caution",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 0.25
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "grouping",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": "offensive"
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "leader_aggression",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": -4
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "leader_goal",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "leader_ignores_keep",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": false
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "leader_value",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 3
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "passive_leader",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": false
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "passive_leader_shares_keep",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": false
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "recruitment_diversity",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 2
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "recruitment_instructions",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": [
                {
                  "tag": "value",
                  "config": {
                    "attrs": {},
                    "children": [
                      {
                        "tag": "recruit",
                        "config": {
                          "attrs": {
                            "importance": 0
                          },
                          "children": []
                        }
                      }
                    ]
                  }
                }
              ]
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "recruitment_more",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "recruitment_pattern",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "recruitment_randomness",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 50
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "recruitment_save_gold",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect"
              },
              "children": [
                {
                  "tag": "value",
                  "config": {
                    "attrs": {
                      "active": 0
                    },
                    "children": []
                  }
                }
              ]
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "retreat_enemy_weight",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 1
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "retreat_factor",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 0.25
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "scout_village_targeting",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 3
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "simple_targeting",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": false
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "support_villages",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": false
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "village_value",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 1
              },
              "children": []
            }
          }
        ]
      }
    },
    {
      "tag": "aspect",
      "config": {
        "attrs": {
          "id": "villages_per_scout",
          "engine": "cpp",
          "name": "composite_aspect"
        },
        "children": [
          {
            "tag": "default",
            "config": {
              "attrs": {
                "engine": "cpp",
                "name": "standard_aspect",
                "value": 4
              },
              "children": []
            }
          }
        ]
      }
    }
  ]
};

/** The 4 named `ai_algorithm=` presets (`data/ai/ais/*.cfg`), each a single `[ai]` config. */
export const AI_ALGORITHM_CONFIGS_JSON: Record<string, WmlConfigJson> = {
  "ai_default_rca": {
    "attrs": {
      "id": "ai_default_rca",
      "description": "Multiplayer_AI^Default AI (RCA)",
      "mp_rank": 1000
    },
    "children": [
      {
        "tag": "stage",
        "config": {
          "attrs": {
            "id": "main_loop",
            "name": "ai_default_rca::candidate_action_evaluation_loop"
          },
          "children": [
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "goto",
                  "engine": "cpp",
                  "name": "ai_default_rca::goto_phase",
                  "max_score": 200000,
                  "score": 200000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "retreat_injured",
                  "engine": "lua",
                  "name": "ai_default_rca::retreat_injured",
                  "max_score": 192000,
                  "location": "ai/lua/ca_retreat_injured.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "spread_poison",
                  "engine": "lua",
                  "name": "ai_default_rca::spread_poison",
                  "max_score": 190000,
                  "location": "ai/lua/ca_spread_poison.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "recruitment",
                  "engine": "cpp",
                  "name": "default_recruitment::recruitment",
                  "max_score": 180000,
                  "score": 180000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_leader_to_goals",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_leader_to_goals_phase",
                  "max_score": 140000,
                  "score": 140000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_leader_to_keep",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_leader_to_keep_phase",
                  "max_score": 120000,
                  "score": 120000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "high_xp_attack",
                  "engine": "lua",
                  "name": "ai_default_rca::high_xp_attack",
                  "location": "ai/lua/ca_high_xp_attack.lua",
                  "max_score": 100010
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "combat",
                  "engine": "cpp",
                  "name": "ai_default_rca::combat_phase",
                  "max_score": 100000,
                  "score": 100000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "place_healers",
                  "engine": "lua",
                  "name": "ai_default_rca::place_healers",
                  "max_score": 96000,
                  "location": "ai/lua/ca_place_healers.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "healing",
                  "engine": "cpp",
                  "name": "ai_default_rca::get_healing_phase",
                  "max_score": 80000,
                  "score": 80000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "villages",
                  "engine": "cpp",
                  "name": "ai_default_rca::get_villages_phase",
                  "max_score": 60000,
                  "score": 60000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_to_targets",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_to_targets_phase",
                  "max_score": 20000,
                  "score": 20000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "leader_shares_keep",
                  "engine": "cpp",
                  "name": "ai_default_rca::leader_shares_keep_phase",
                  "max_score": 10000,
                  "score": 10000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_to_any_enemy",
                  "engine": "lua",
                  "name": "ai_default_rca::move_to_any_enemy",
                  "max_score": 1000,
                  "location": "ai/lua/ca_move_to_any_enemy.lua"
                },
                "children": []
              }
            }
          ]
        }
      }
    ]
  },
  "ai_default_rca_1_14": {
    "attrs": {
      "id": "ai_default_rca_1_14",
      "description": "Multiplayer_AI^Old Default AI (1.14 version)",
      "mp_rank": 1005
    },
    "children": [
      {
        "tag": "stage",
        "config": {
          "attrs": {
            "id": "main_loop",
            "name": "ai_default_rca::candidate_action_evaluation_loop"
          },
          "children": [
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "goto",
                  "engine": "cpp",
                  "name": "ai_default_rca::goto_phase",
                  "max_score": 200000,
                  "score": 200000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "recruitment",
                  "engine": "cpp",
                  "name": "default_recruitment::recruitment",
                  "max_score": 180000,
                  "score": 180000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_leader_to_goals",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_leader_to_goals_phase",
                  "max_score": 140000,
                  "score": 140000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_leader_to_keep",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_leader_to_keep_phase",
                  "max_score": 120000,
                  "score": 120000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "high_xp_attack",
                  "engine": "lua",
                  "name": "ai_default_rca::high_xp_attack",
                  "location": "ai/lua/ca_high_xp_attack.lua",
                  "max_score": 100010
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "combat",
                  "engine": "cpp",
                  "name": "ai_default_rca::combat_phase",
                  "max_score": 100000,
                  "score": 100000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "healing",
                  "engine": "cpp",
                  "name": "ai_default_rca::get_healing_phase",
                  "max_score": 80000,
                  "score": 80000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "villages",
                  "engine": "cpp",
                  "name": "ai_default_rca::get_villages_phase",
                  "max_score": 60000,
                  "score": 60000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "retreat",
                  "engine": "cpp",
                  "name": "ai_default_rca::retreat_phase",
                  "max_score": 40000,
                  "score": 40000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_to_targets",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_to_targets_phase",
                  "max_score": 20000,
                  "score": 20000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "leader_shares_keep",
                  "engine": "cpp",
                  "name": "ai_default_rca::leader_shares_keep_phase",
                  "max_score": 10000,
                  "score": 10000
                },
                "children": []
              }
            }
          ]
        }
      }
    ]
  },
  "ai_experimental": {
    "attrs": {
      "id": "experimental_ai",
      "description": "Multiplayer_AI^Experimental AI",
      "mp_rank": 1010
    },
    "children": [
      {
        "tag": "stage",
        "config": {
          "attrs": {
            "id": "main_loop",
            "name": "ai_default_rca::candidate_action_evaluation_loop"
          },
          "children": [
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "goto",
                  "engine": "cpp",
                  "name": "ai_default_rca::goto_phase",
                  "max_score": 200000,
                  "score": 200000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "recruit_rushers",
                  "engine": "lua",
                  "name": "recruit_rushers",
                  "max_score": 196000,
                  "location": "ai/lua/ca_recruit_rushers.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "castle_switch",
                  "engine": "lua",
                  "name": "ai_default_rca::castle_switch",
                  "max_score": 195000,
                  "location": "ai/lua/ca_castle_switch.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "retreat_injured",
                  "engine": "lua",
                  "name": "ai_default_rca::retreat_injured",
                  "max_score": 192000,
                  "location": "ai/lua/ca_retreat_injured.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "grab_villages",
                  "engine": "lua",
                  "name": "grab_villages",
                  "max_score": 191000,
                  "location": "ai/lua/ca_grab_villages.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "spread_poison",
                  "engine": "lua",
                  "name": "ai_default_rca::spread_poison",
                  "max_score": 190000,
                  "location": "ai/lua/ca_spread_poison.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_leader_to_goals",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_leader_to_goals_phase",
                  "max_score": 140000,
                  "score": 140000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_leader_to_keep",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_leader_to_keep_phase",
                  "max_score": 120000,
                  "score": 120000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "high_xp_attack",
                  "engine": "lua",
                  "name": "ai_default_rca::high_xp_attack",
                  "location": "ai/lua/ca_high_xp_attack.lua",
                  "max_score": 100010
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "combat",
                  "engine": "cpp",
                  "name": "ai_default_rca::combat_phase",
                  "max_score": 100000,
                  "score": 100000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "place_healers",
                  "engine": "lua",
                  "name": "ai_default_rca::place_healers",
                  "max_score": 96000,
                  "location": "ai/lua/ca_place_healers.lua"
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "healing",
                  "engine": "cpp",
                  "name": "ai_default_rca::get_healing_phase",
                  "max_score": 80000,
                  "score": 80000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_to_targets",
                  "engine": "cpp",
                  "name": "ai_default_rca::move_to_targets_phase",
                  "max_score": 20000,
                  "score": 20000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "leader_shares_keep",
                  "engine": "cpp",
                  "name": "ai_default_rca::leader_shares_keep_phase",
                  "max_score": 10000,
                  "score": 10000
                },
                "children": []
              }
            },
            {
              "tag": "candidate_action",
              "config": {
                "attrs": {
                  "id": "move_to_any_enemy",
                  "engine": "lua",
                  "name": "ai_default_rca::move_to_any_enemy",
                  "max_score": 1000,
                  "location": "ai/lua/ca_move_to_any_enemy.lua"
                },
                "children": []
              }
            }
          ]
        }
      }
    ]
  },
  "idle_ai": {
    "attrs": {
      "id": "idle_ai",
      "description": "Multiplayer_AI^Dev AI: Idle AI",
      "hidden": true
    },
    "children": [
      {
        "tag": "stage",
        "config": {
          "attrs": {
            "name": "empty"
          },
          "children": []
        }
      }
    ]
  }
};
